name: Pull Request

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: "super_enum_generator"
        run: pub get
      - name: format
        run: dartfmt -n --set-exit-if-changed .
      - name: Run tests
        working-directory: "super_enum_generator"
        run: pub run test
      - name: Collect coverage
        working-directory: "super_enum_generator"
        run: ./tool/run_coverage.sh