name: Dart CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        working-directory: "super_enum_generator"
        run: pub get
      - name: format
        run: dartfmt -n --set-exit-if-changed .
      - name: Run tests
        working-directory: "super_enum_generator"
        run: pub run test
      - name: Collect coverage
        working-directory: "super_enum_generator"
        run: ./tool/run_coverage.sh
      - name: Report CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: super_enum_generator/out/coverage/lcov.info